### ISSUE TITLE
Setting files are not installed via pip

### ISSUE THREAD

**Issue by henhuy** [rl-institut/oemof-B3#175]
See:
```
Traceback (most recent call last):
  File "scripts/plot_scalar_results.py", line 24, in <module>
    import oemoflex.tools.plots as plots
  File "/home/local/RL-INSTITUT/hendrik.huyskens/miniconda3/envs/oemof-B3/lib/python3.8/site-packages/oemoflex/tools/plots.py", line 13, in <module>
    default_labels_dict = helpers.load_yaml(os.path.join(dir_name, "labels.yaml"))
  File "/home/local/RL-INSTITUT/hendrik.huyskens/miniconda3/envs/oemof-B3/lib/python3.8/site-packages/oemoflex/tools/helpers.py", line 9, in load_yaml
    with open(file_path, "r") as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/local/RL-INSTITUT/hendrik.huyskens/miniconda3/envs/oemof-B3/lib/python3.8/site-packages/oemoflex/tools/labels.yaml'
```

Solution: Add files to MANIFEST.in file

**Comment by jnnr** [comment]
Is this still open, @henhuy?

**Comment by henhuy** [comment]
Sorry, as you can see in error message - this belongs to oemoflex. Will fix it there.

**Comment by jnnr** [comment]
@henhuy: Seems to be done already https://github.com/rl-institut/oemoflex/pull/56

**Comment by henhuy** [comment]
You are right - this should be fine now.
