### ISSUE TITLE
Windows installation error

### ISSUE THREAD

**Issue by chrwm** [rl-institut/oemof-B3#326]
Updating charset-normalizer (3.1.0 -> 3.0.1): Failed

```
• Updating charset-normalizer (3.1.0 -> 3.0.1): Failed

  CalledProcessError

  Command '['C:\\Users\\christoph.muschner\\Miniconda3\\envs\\oemof-B3\\python.exe', '-m', 'pip', 'uninstall', 'charset-normalizer', '-y']' returned non-zero exit status 2.

  at ~\Miniconda3\envs\oemof-B3\lib\subprocess.py:516 in run
       512│             # We don't call process.wait() as .__exit__ does that for us.
       513│             raise
       514│         retcode = process.poll()
       515│         if check and retcode:
    →  516│             raise CalledProcessError(retcode, process.args,
       517│                                      output=stdout, stderr=stderr)
       518│     return CompletedProcess(process.args, retcode, stdout, stderr)
       519│
       520│

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['C:\\Users\\christoph.muschner\\Miniconda3\\envs\\oemof-B3\\python.exe', '-m', 'pip', 'uninstall', 'charset-normalizer', '-y'] errored with the following return code 2

  Output:
  Found existing installation: charset-normalizer 3.1.0
  Uninstalling charset-normalizer-3.1.0:
    Successfully uninstalled charset-normalizer-3.1.0
  ERROR: Exception:
  Traceback (most recent call last):
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\site-packages\pip\_internal\cli\base_command.py", line 160, in exc_logging_wrapper
      status = run_func(*args)
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\site-packages\pip\_internal\commands\uninstall.py", line 110, in run
      uninstall_pathset.commit()
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\site-packages\pip\_internal\req\req_uninstall.py", line 424, in commit
      self._moved_paths.commit()
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\site-packages\pip\_internal\req\req_uninstall.py", line 277, in commit
      save_dir.cleanup()
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup
      rmtree(self._path)
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 328, in wrapped_f
      return self(f, *args, **kw)
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 408, in __call__
      do = self.iter(retry_state=retry_state)
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 364, in iter
      raise retry_exc.reraise()
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 197, in reraise
      raise self.last_attempt.result()
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\concurrent\futures\_base.py", line 437, in result
      return self.__get_result()
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\concurrent\futures\_base.py", line 389, in __get_result
      raise self._exception
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 411, in __call__
      result = fn(*args, **kwargs)
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\site-packages\pip\_internal\utils\misc.py", line 129, in rmtree
      shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\shutil.py", line 740, in rmtree
      return _rmtree_unsafe(path, onerror)
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\shutil.py", line 618, in _rmtree_unsafe
      onerror(os.unlink, fullname, sys.exc_info())
    File "C:\Users\christoph.muschner\Miniconda3\envs\oemof-B3\lib\shutil.py", line 616, in _rmtree_unsafe
      os.unlink(fullname)
  PermissionError: [WinError 5] Zugriff verweigert: 'C:\\Users\\christoph.muschner\\Miniconda3\\envs\\oemof-b3\\Lib\\site-packages\\~-arset_normalizer\\md.cp38-win_amd64.pyd'


  at ~\Miniconda3\envs\oemof-B3\lib\site-packages\poetry\utils\env.py:1545 in _run
      1541│                 return subprocess.call(cmd, stderr=stderr, env=env, **kwargs)
      1542│             else:
      1543│                 output = subprocess.check_output(cmd, stderr=stderr, env=env, **kwargs)
      1544│         except CalledProcessError as e:
    → 1545│             raise EnvCommandError(e, input=input_)
      1546│
      1547│         return decode(output)
      1548│
      1549│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:
```

Solution: 

1. Run miniconda as admin
2. `pip install charset_normalizer` manually

```
ModuleNotFoundError: No module named 'chardet'
```

Solution: 

1 `pip install chardet` manually

**Comment by chrwm** [comment]
Solution: 

1. Run miniconda as admin
2. `pip install chardet` manually
